# Write your MySQL query statement below
SELECT DEPARTMENT.NAME "Department", EMPLOYEE.NAME "Employee", EMPLOYEE.SALARY "Salary"
FROM EMPLOYEE
JOIN (
    SELECT DEPARTMENTID, MAX(SALARY) SALARY
    FROM EMPLOYEE
    GROUP BY DEPARTMENTID
) MAAX ON EMPLOYEE.DEPARTMENTID = MAAX.DEPARTMENTID
JOIN DEPARTMENT ON EMPLOYEE.DEPARTMENTID = DEPARTMENT.ID
WHERE EMPLOYEE.SALARY = MAAX.SALARY
