# Write your MySQL query statement below
SELECT DEPARTMENT.NAME "Department", EMPLOYEE.NAME "Employee", EMPLOYEE.SALARY "Salary"
FROM EMPLOYEE
JOIN DEPARTMENT ON EMPLOYEE.DEPARTMENTID = DEPARTMENT.ID
WHERE (DEPARTMENTID, SALARY) IN (
    SELECT DEPARTMENTID, MAX(SALARY) SALARY
    FROM EMPLOYEE
    GROUP BY DEPARTMENTID
) 
